### ISSUE TITLE
Pulse Audio Volume Level with Multiple devices

### ISSUE THREAD

**Issue by kispin** [velovix/awesome.volume-widget#2]
Hi,

I have 2 audio devices and my system happens to mainly use the secondary one and hence that is the one I am using for the widget.

I noticed however that the widget was using the first rather than the second.

I have identified and fixed the code on my end and thought I would pass the fix on (not sure of the protocol for this)

Line 83 needs to change from
`result = run("pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \\([0-9][0-9]*\\)%.*,\\1,'")`

to the following to fix the fault

`result = run("pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( " .. self.device .. " + 1 )) | tail -n 1 | sed -e 's,.* \\([0-9][0-9]*\\)%.*,\\1,'")`

**Comment by velovix** [comment]
This is great, thanks! Would you mind creating a pull request?

**Comment by kispin** [comment]
I am not certain how to do that and my local version is kinda modified (I have added numbers instead of the icon as I prefer that)

**Comment by velovix** [comment]
I finally got around to implementing this fix upstream, see bf6bd5ba94a3f16af4880a1e89ad93c1d4e8530b

Thank you for the suggestion!
